[[rules]]
regex = 'password|api_key|secret'
description = "Potential sensitive information"
tags = ["high_severity"]

[[rules]]
regex = 'access_key|private_key'
description = "Potential access keys"
tags = ["high_severity"]

[[rules]]
file = 'false_report.txt'
description = "Text file containing potential secrets"
tags = ["medium_severity"]
