name: gitleaks
on: [pull_request, push, workflow_dispatch]

jobs:
  scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Owner and Repo
        id: extract
        run: |
          REPO_URL='https://github.com/sidwar76/hashedin.git'
          REPO_NAME=$(basename $REPO_URL .git)
          OWNER=$(echo $REPO_URL | sed 's/.*github.com\///' | sed 's/\/.*//')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "OWNER=$OWNER" >> $GITHUB_ENV

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: gitleaks.toml
          repo: ${{ env.OWNER }}/${{ env.REPO_NAME }}
        env:
          GITHUB_TOKEN: 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

          

