name: gitleaks
on: [pull_request, push, workflow_dispatch]

jobs:
  scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: https://github.com/sidwar76/hashedin.git
          ref: master # Replace 'main' with the target branch name

      - uses: gitleaks/gitleaks-action@v2
        with:
          config-path: gitleaks.toml
        env:
          GITHUB_TOKEN: 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
          

