name: TruffleHog Scan

on:
  push:
    branches:
      - master

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install TruffleHog
        run: pip install truffleHog

      - name: Create TruffleHog Rules File
        run: |
          echo '{
            "rules": [
              {
                "regex": "(password|api_key|secret)",
                "name": "Sensitive Information",
                "severity": "HIGH"
              },
              {
                "regex": "(access_key|private_key)",
                "name": "Access Keys",
                "severity": "HIGH"
              },
              {
                "regex": "(db_username|db_password)",
                "name": "Database Credentials",
                "severity": "MEDIUM"
              },
              {
                "file": "(\\.env|config\\.json)",
                "name": "Configuration Files",
                "severity": "MEDIUM"
              }
            ]
          }' > $GITHUB_WORKSPACE/trufflehog-rules.json
      - name: List Repository Files
        run: ls $GITHUB_WORKSPACE
      
      - name: Print TruffleHog Rules File
        run: cat $GITHUB_WORKSPACE/trufflehog-rules.json



      - name: TruffleHog Scan
        run: |
          trufflehog /github/workspace --json --rules $GITHUB_WORKSPACE/trufflehog-rules.json > trufflehog-report.json

      - name: Upload TruffleHog Scan Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-scan-report
          path: trufflehog-report.json


