name: TruffleHog Scan

on:
  push:
    branches:
      - master

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install TruffleHog Docker image
        run: docker pull trufflesecurity/trufflehog:latest

      - name: Create TruffleHog Rules File
        run: |
          echo '{
            "rules": [
              {
                "regex": "(password|api_key|secret)",
                "name": "Sensitive Information",
                "severity": "HIGH"
              },
              {
                "regex": "(access_key|private_key)",
                "name": "Access Keys",
                "severity": "HIGH"
              },
              {
                "regex": "(db_username|db_password)",
                "name": "Database Credentials",
                "severity": "MEDIUM"
              },
              {
                "file": "(\\.env|config\\.json)",
                "name": "Configuration Files",
                "severity": "MEDIUM"
              }
            ]
          }' > $GITHUB_WORKSPACE/trufflehog-rules.json

      - name: TruffleHog Scan
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/src trufflesecurity/trufflehog:latest /src --json --rules /src/trufflehog-rules.json

      - name: Upload TruffleHog Scan Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-scan-report
          path: trufflehog-report.json
