name: TruffleHog Scan with regex
on:
  push:
    branches:
      - master

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest

    steps:
      - name: TruffleHog Scan
        run: |
          docker run -t gesellix/trufflehog --json https://github.com/sidwar76/DVWA.git > trufflehog-report.json
        # Publish the TruffleHog report as an artifact
          

      - name: Upload TruffleHog Scan Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-scan-report
          path: trufflehog-report.json

